server:
  port: 8003

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8
    username: root
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update